export const LOAD_USER_INFO = 'LOAD_USER_INFO'
export const LOAD_USER_INFO_RESOLVE = 'LOAD_USER_INFO_RESOLVE'

export const SEARCH_USER = 'SEARCH_USER'
export const SEARCH_USER_RESOLVE = 'SEARCH_USER_RESOLVE'

export const LOAD_STARRED_REPOS = 'LOAD_STARRED_REPOS'
export const LOAD_STARRED_REPOS_RESOLVE = 'LOAD_STARRED_REPOS_RESOLVE'
export const LOAD_REPO_INFO = 'LOAD_REPO_INFO'
export const LOAD_REPO_INFO_RESOLVE = 'LOAD_REPO_INFO_RESOLVE'
